#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 pccxai

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOC_PATH="$ROOT/docs/test-coverage.md"
STRICT=0

usage() {
    cat <<'USAGE'
Usage: scripts/coverage_summary.sh [--strict]

Runs coverage over the KV260/offline mock test slice and rewrites
docs/test-coverage.md with a module-level coverage snapshot.

Options:
  --strict   fail if any tracked slice test or module is missing
  -h, --help show this help
USAGE
}

for arg in "$@"; do
    case "$arg" in
        --strict)
            STRICT=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
done

cd "$ROOT"

if ! python3 -m coverage --version >/dev/null 2>&1; then
    cat >&2 <<'EOF'
python3 -m coverage is required.
Install coverage in your active Python environment, then rerun:
  python3 -m pip install coverage
EOF
    exit 2
fi

SLICE_ROWS=(
    "#70|scripts/tests/kv260_readiness_scaffold_test.py|contracts/kv260_readiness_scaffold.py"
    "#72|scripts/tests/kv260_serial_connection_test.py|contracts/kv260_serial_connection.py"
    "#73|scripts/tests/gemma_weight_prep_contract_test.py|contracts/gemma_weight_prep_contract.py"
    "#74 #75|scripts/tests/axi_cmd_mock_backend_test.py|contracts/axi_cmd_channel.py"
    "#75|scripts/tests/dummy_e2e_contract_test.py|contracts/dummy_e2e_contract.py"
    "#77 #80|scripts/tests/kv260_connection_mock_test.py|contracts/kv260_connection_mock.py"
    "#78 #79|scripts/tests/trace_capture_client_test.py|contracts/trace_capture_client.py"
    "#81|scripts/tests/full_mock_integration_test.py|"
)

present_tests=()
missing_rows=()
module_files=()
seen_modules=" "

for row in "${SLICE_ROWS[@]}"; do
    IFS='|' read -r prs test_file module_file <<<"$row"
    if [ ! -f "$test_file" ]; then
        missing_rows+=("$row")
        continue
    fi
    present_tests+=("$test_file")
    if [ -n "$module_file" ]; then
        if [ ! -f "$module_file" ]; then
            missing_rows+=("$row")
            continue
        fi
        case "$seen_modules" in
            *" $module_file "*) ;;
            *)
                module_files+=("$module_file")
                seen_modules="$seen_modules$module_file "
                ;;
        esac
    fi
done

if [ "${#present_tests[@]}" -eq 0 ]; then
    echo "no slice tests are present in this checkout" >&2
    exit 1
fi

if [ "$STRICT" -eq 1 ] && [ "${#missing_rows[@]}" -ne 0 ]; then
    echo "missing slice inputs:" >&2
    for row in "${missing_rows[@]}"; do
        IFS='|' read -r prs test_file module_file <<<"$row"
        printf '  %s %s %s\n' "$prs" "$test_file" "$module_file" >&2
    done
    exit 1
fi

coverage_json="$(mktemp)"
doc_tmp="$(mktemp)"
trap 'rm -f "$coverage_json" "$doc_tmp"' EXIT

python3 -m coverage erase
for test_file in "${present_tests[@]}"; do
    env -u KVFPGA_HOST \
        -u KVFPGA_TTY \
        -u KVFPGA_USER \
        -u KVFPGA_PASSWORD \
        python3 -m coverage run --branch --source=contracts --append "$test_file"
done

python3 -m coverage json -o "$coverage_json" "${module_files[@]}" >/dev/null
overall_percent="$(
    python3 -m coverage report "${module_files[@]}" |
        awk '/^TOTAL[[:space:]]/ {print $NF}'
)"

{
    cat <<EOF
# Test Coverage Snapshot

This snapshot is generated by \`scripts/coverage_summary.sh\` for the KV260/offline mock coverage slice.
It is a source-level coverage summary for the modules exercised by the currently checked-out slice tests.

## How to regenerate

\`\`\`sh
python3 -m pip install coverage
./scripts/coverage_summary.sh
\`\`\`

Use \`./scripts/coverage_summary.sh --strict\` after every referenced slice branch has landed in the checkout.

## Slice inputs

| PR refs | Test file | Module | Snapshot status |
| --- | --- | --- | --- |
EOF
    for row in "${SLICE_ROWS[@]}"; do
        IFS='|' read -r prs test_file module_file <<<"$row"
        status="covered"
        if [ ! -f "$test_file" ]; then
            status="missing from checkout"
        elif [ -n "$module_file" ] && [ ! -f "$module_file" ]; then
            status="module missing from checkout"
        fi
        printf '| %s | `%s` | ' "$prs" "$test_file"
        if [ -n "$module_file" ]; then
            printf '`%s`' "$module_file"
        else
            printf 'shared modules'
        fi
        printf ' | %s |\n' "$status"
    done

    cat <<EOF

The PR #79 and #80 slices extend tests introduced by earlier PRs, so the table deduplicates those test files.
Rows marked missing are not included in the numeric snapshot for this checkout.

## Module line counts

EOF
    python3 - "$coverage_json" "${module_files[@]}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

coverage_path = Path(sys.argv[1])
module_files = sys.argv[2:]
data = json.loads(coverage_path.read_text(encoding="utf-8"))

print("| Module | Physical lines | Statements | Missing | Branches | Coverage |")
print("| --- | ---: | ---: | ---: | ---: | ---: |")
for module in module_files:
    path = Path(module)
    summary = data["files"][module]["summary"]
    physical_lines = len(path.read_text(encoding="utf-8").splitlines())
    print(
        "| `{}` | {} | {} | {} | {} | {}% |".format(
            module,
            physical_lines,
            summary["num_statements"],
            summary["missing_lines"],
            summary["num_branches"],
            summary["percent_covered_display"],
        )
    )
PY

    cat <<EOF

## Coverage report

Overall coverage for the included modules: **$overall_percent**

EOF
    python3 -m coverage report --show-missing --format=markdown "${module_files[@]}"
} > "$doc_tmp"

mv "$doc_tmp" "$DOC_PATH"
python3 -m coverage erase
printf 'coverage summary written to %s\n' "$DOC_PATH"
printf 'overall coverage: %s\n' "$overall_percent"
